- name: testing printing
  hosts: node1
  tasks:
    - name: showing a message
      ansible.builtin.debug:
        msg: "echo helloworld"
  
- name: pinging
  hosts: local
  tasks:
    - name: pinging
      ansible.builtin.ping:


- name: installing nginx
  hosts: node1
  become: yes
  tasks:
    - name: installing nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: starting service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
