- name: installing packs using loops
  hosts: node1
  become: yes
  tasks:
  - name: installing {{ item }}
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - git
    - zip